// src/modules/Brand.tsx
import React from "react";
import { Swiper, SwiperSlide } from "swiper/react";
import data from "../data/data.json"; // Sesuaikan path import
import { Data } from "../types"
import { Autoplay } from "swiper/modules";

const Brand: React.FC = () => {
  const brands: Data = data;

  return (
    <>
      {/* Brand area start */}
      <section className="main-brand__area gray-bg section-space-bottom-2">
        <div className="brand__area">
          <div className="container">
            <div className="row">
              <div className="col-12">
                <Swiper
                  modules={[Autoplay]}
                  direction="horizontal"
                  className="brand__active wow fadeIn"
                  data-wow-delay=".3s"
                  spaceBetween={5}
                  slidesOffsetBefore={5}
                  slidesOffsetAfter={5}
                  loop
                  autoplay={{
                    delay: 3000, // Set delay between slides to 3000ms (3 seconds)
                    disableOnInteraction: false, // Keeps autoplay running even after user interaction
                  }}
                  breakpoints={{
                    320: {
                      slidesPerView: 1,
                    },
                    480: {
                      slidesPerView: 2,
                    },
                    768: {
                      slidesPerView: 3,
                    },
                    1024: {
                      slidesPerView: 4,
                    },
                    1200: {
                      slidesPerView: 5,
                    },
                  }}
                >
                  {brands.brands.map((brand) => (
                    <SwiperSlide key={brand.id}>
                    <div
                      className="brand__item text-center  wow fadeIn animated"
                      data-wow-delay=".1s"
                    >
                      <div className="brand__thumb">
                        <a href={brand.link} target="_blank">
                          <img
                            className="img-fluid"
                            src={brand.image}
                            alt="image not found"
                          />
                        </a>
                      </div>
                    </div>
                  </SwiperSlide>
                  ))}
                </Swiper>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Brand;

// src/components/shared/Brand.vue
<template>
  <!-- Brand area start -->
  <section class="main-brand__area section-space-bottom">
    <div class="brand__area">
      <div class="container">
        <div class="row">
          <div class="col-12">
            <swiper class="brand__active wow fadeIn" data-wow-delay=".2s" :slides-per-view="5" :space-between="30" :loop="true">
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".3s"
                  >
                    <div class="brand__thumb">
                      <a href="https://segment.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-1.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".4s"
                  >
                    <div class="brand__thumb">
                      <a href="https://www.splunk.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-2.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".5s"
                  >
                    <div class="brand__thumb">
                      <a href="https://www.hubspot.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-3.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".6s"
                  >
                    <div class="brand__thumb">
                      <a href="https://app.asana.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-4.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".7s"
                  >
                    <div class="brand__thumb">
                      <a href="https://www.airtasker.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-5.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>

                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".3s"
                  >
                    <div class="brand__thumb">
                      <a href="https://segment.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-1.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".4s"
                  >
                    <div class="brand__thumb">
                      <a href="https://www.splunk.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-2.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".5s"
                  >
                    <div class="brand__thumb">
                      <a href="https://www.hubspot.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-3.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".6s"
                  >
                    <div class="brand__thumb">
                      <a href="https://app.asana.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-4.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
                <swiper-slide>
                  <div
                    class="brand__item text-center wow fadeIn animated"
                    data-wow-delay=".7s"
                  >
                    <div class="brand__thumb">
                      <a href="https://www.airtasker.com/"
                        ><img
                          class="img-fluid"
                          src="/assets/imgs/brands/home2-companey-brands-image-5.png"
                          alt="image not found"
                      /></a>
                    </div>
                  </div>
                </swiper-slide>
            </swiper>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!-- Brand area end -->
</template>

<script>
import { Swiper, SwiperSlide } from "swiper/vue";

export default {
  name: "Brand",
  components: {
    Swiper,
    SwiperSlide,
  },
};
</script>

<style scoped></style>
